services:
  database:
    image: mysql:5.7.44
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=strapi
      - MYSQL_USER=strapi
      - MYSQL_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  strapi:
    container_name: strapi
    build: ./services/strapi-cms
    image: strapi:5
    restart: unless-stopped
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=secret
      - JWT_SECRET=mysecrettoken
      - ADMIN_JWT_SECRET=myadminsecrettoken
      - APP_KEYS=key1,key2,key3,key4
      - NODE_ENV=develop
    volumes:
      - ./services/strapi-cms/config:/opt/app/config
      - ./services/strapi-cms/public/uploads:/opt/app/public/uploads
      - ./services/strapi-cms/database:/opt/app/database
    ports:
      - "1337:1337"
    depends_on:
      - database
